### ISSUE TITLE
Cannot login with SQLITE3 database and authentication

### ISSUE THREAD

**Issue by hufon** [babelouest/angharad#1]
I've got this error in the log

2016-10-23T20:56:53 - Angharad ERROR: Error executing sql query
2016-10-23T20:56:53 - Angharad DEBUG: Error code: 1, message: "no such function: PASSWORD"
2016-10-23T20:56:53 - Angharad DEBUG: Query: "SELECT \* FROM a_user WHERE au_enabled = '1' AND au_login = 'test' AND au_password = PASSWORD('test')  "
2016-10-23T20:56:53 - Angharad ERROR: Error in database while executing query

It seems that SQLITE3 doesn't know password function

**Comment by babelouest** [comment]
You're right, sqlite3 doesn't implement password or hash functions.

I implemented db stored users but without the need since I use an LDAP server, and the db users tests were made with the mysql database...

I see that there is no out of the box solution for this problem. What I could think of without making angarad too overkill is one of the following solutions:
- Store passwords without protection in the database
- Store the using hex or base64, no encryption, but at least it's not easily readable
- Add a simple hashing function like one of these: http://stackoverflow.com/questions/14409466/simple-hash-functions

None of those solutions are secured, but I wouldn't like having openssl library mandatory in angharad, unless you know a simple implementation of sha1 or md5 that could be added and with a compatible licence.

The best case here would be the simple hashing function, but if you have other ideas, I'm open to suggestions.

**Comment by babelouest** [comment]
I made a temporary fix with https://github.com/babelouest/angharad/commit/d2f68ce3efe8e935f86b7041f1c2a5b995ee9321
the password is stored using SQLite HEX() so at least you can go further, I also fixed the session management for SQLite which was bugged too...

**Comment by babelouest** [comment]
To add a default user in the database before starting the application, you can use the following example:

``` sql
insert into a_user (au_login, au_password, au_enabled) values ('admin', HEX('password'), 1);
```

**Comment by hufon** [comment]
Ok, thanks i'll test this asap.
I've seen the problem with tokens too. I think sqlite support is very important, because most of user (like me) want to run on a raspberry pi (i've a 256Mo model) without LDAP and MySQL.

**Comment by hufon** [comment]
This one ?
http://people.csail.mit.edu/rivest/Md5.c

or this one (openssl)

```
include <stdio.h>
#include <stdlib.h>
#include <string.h>
#if defined(__APPLE__)
#  define COMMON_DIGEST_FOR_OPENSSL
#  include <CommonCrypto/CommonDigest.h>
#  define SHA1 CC_SHA1
#else
#  include <openssl/md5.h>
#endif

char *str2md5(const char *str, int length) {
    int n;
    MD5_CTX c;
    unsigned char digest[16];
    char *out = (char*)malloc(33);

    MD5_Init(&c);

    while (length > 0) {
        if (length > 512) {
            MD5_Update(&c, str, 512);
        } else {
            MD5_Update(&c, str, length);
        }
        length -= 512;
        str += 512;
    }

    MD5_Final(digest, &c);

    for (n = 0; n < 16; ++n) {
        snprintf(&(out[n*2]), 16*2, "%02x", (unsigned int)digest[n]);
    }

    return out;
}

    int main(int argc, char **argv) {
        char *output = str2md5("hello", strlen("hello"));
        printf("%s\n", output);
        free(output);
        return 0;
    }
```

**Comment by babelouest** [comment]
Thanks, I'll try the first one when I'll have a minute.

Let me know if the patch works

**Comment by hufon** [comment]
Ok, the patch works... let's now implementing a benoic devis, communicating with my arduino on i2c port...

**Comment by babelouest** [comment]
I reopen it since there still are some problems to fix:
- hash passwords in sqlite
- fix timestamps with sqlite database

**Comment by babelouest** [comment]
I made some modifications in the code to fix those issues here: https://github.com/babelouest/angharad/commit/a04a17327814a1fc811f3edefa860fd4b0ad0891

You must re-run the db creation script `angharad.sqlite3.sql` for it to work since I updated the `a_user` and `b_monitor` tables.

I'm closing this issue, let me know if yoy have other problems with sqlite3 dabaatse.
